### ISSUE TITLE
Image not showing

### ISSUE THREAD

**Issue by AtomicSlayerX** [kinghacker0/WishFish#17]
After I download the image i get from my victim it shows a black image everytime, i have tried it on my phone but no change

**Comment by AadvikRaj** [comment]
> After I download the image i get from my victim it shows a black image everytime, i have tried it on my phone but no change

You may close this now it's working

**Comment by Naveenkumar021** [comment]
NOT WORKING the image i get from my victim it shows a black image everytime, i have tried it on my phone but no change

**Comment by Naveenkumar021** [comment]
I HAVE BEEN USED BEFORE 4 MONTHS WORKED FINE BUT NOW NOT WORKING

**Comment by RDJ3000** [comment]
> NOT WORKING the image i get from my victim it shows a black image everytime, i have tried it on my phone but no change

It does not shows gallery picture it will show the pic from front camera (at the time)

**Comment by Mr-Lr** [comment]
![Screenshot_٢٠٢٢٠١١٩-١٦٥٦٠٠](https://user-images.githubusercontent.com/97852335/150157562-e85199fd-7e64-4ad1-a8cc-7c1d8e6f7795.png)
ماهي الخطوه التاليه يااصدقاء
