### ISSUE TITLE
Does not show the link (traductor)

### ISSUE THREAD

**Issue by DImitriXxRUSA** [kinghacker0/WishFish#25]
It doesn't show me the link, I'm cell phone, Termux use (traductor

**Comment by kankereend** [comment]
> It doesn't show me the link, I'm cell phone, Termux use (traductor

You need to turn on hotspot before and while running the script

**Comment by 14-Munoha** [comment]
> > It doesn't show me the link, I'm cell phone, Termux use (traductor
> 
> You need to turn on hotspot before and while running the script

How ?

**Comment by Debmaly1234** [comment]
I am connected with my WiFi ... how can I connect hotspot??

**Comment by Milankanth** [comment]
I couldn't get link
