### ISSUE TITLE
just 1 problem

### ISSUE THREAD

**Issue by adityadevp** [kinghacker0/WishFish#40]
problem is it doesnt creating a link after choosing Ngrok and Serveo either 😑

**Comment by shanky-cyber** [comment]
Same bro

**Comment by Rademenes16** [comment]
other cam apps also stopped working
seems like its global issue

**Comment by Rademenes16** [comment]
here are 2 apps i found with same problem
https://github.com/noob-hackers/grabcam/issues
https://github.com/LiNuX-Mallu/CAM-DUMPER/issues/18

**Comment by LiNuX-Mallu** [comment]
> here are 2 apps i found with same problem
> https://github.com/noob-hackers/grabcam/issues
> [LiNuX-Mallu/CAM-DUMPER#18](https://github.com/LiNuX-Mallu/CAM-DUMPER/issues/18)

Actually i ve fixed my tool 
It is working .

**Comment by LiNuX-Mallu** [comment]
https://github.com/LiNuX-Mallu/CAM-DUMPER/issues/17#issuecomment-913815129

Try this method .
Will work for all tool .

**Comment by orestescaminha** [comment]
Needs ngrok configuration https://dashboard.ngrok.com/get-started/setup

**Comment by Mr-Lr** [comment]
![Screenshot_٢٠٢٢٠١١٩-١٦٥٦٠٠](https://user-images.githubusercontent.com/97852335/150155874-4f9ab318-acc5-40db-8ee6-e39b8a156edb.png)
