### ISSUE TITLE
Blank link

### ISSUE THREAD

**Issue by The-Memzer** [kinghacker0/WishFish#45]
__          _ _     _      ______ _     _          
 \ \        / (_)   | |    |  ____(_)   | |         
  \ \  /\  / / _ ___| | __ | |__   _ ___| |__       
   \ \/  \/ / | / __| '_  ||  __| | / __| '_ \      
    \  /\  /  | \__ \ | | || |    | \__ \ | | |     
     \/  \/   |_|___/_| |_||_|    |_|___/_| |_| v2.0
 Website :- www.hackersking.in  
 v2.0 Coded By github.com/kinghacker0  

[01] Serveo.net
[02] Ngrok

[+] Choose a Port Forwarding option: 2
[+] Downloading Ngrok...
[+] Starting php server...
[+] Starting ngrok server...
[*] Direct link: 

[*] Waiting targets, Press Ctrl + C to exit...
same with option 1

**Comment by abhi415129** [comment]
Why direct link is blank?
