### ISSUE TITLE
Link 

### ISSUE THREAD

**Issue by rekhaptl** [kinghacker0/WishFish#47]
I'm not getting link plz help

**Comment by ostronic** [comment]
Try turning on your hotspot

**Comment by Mr-Lr** [comment]
didn't work

**Comment by Mr-Lr** [comment]
![Uploading Screenshot_٢٠٢٢٠١٢١-١٤٠٤٣٠.png…]()

**Comment by ostronic** [comment]
make sure you are logged in on Ngrokj.
you can try getting link from there too
